server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arzooo
    username: root
    password: Path@2014
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  aop:
    proxy-target-class: true

  servlet:
    multipart:
       max-file-size: 5MB
       max-request-size: 5MB
file:
  upload:
    path: '/var/lib/jenkins/workspace/arzoo/arzoo_images/'

